id: redash
name: Redash
description: |
  Redash integration
blocks:
  - title: Overview
    content: |+
      Integration with Redash allows users to retrieve information about queries, dashboards, and datasources.
      Visualizing this data in the ODD Platform provides a comprehensive overview of the Redash environment, including lineage and impact analysis.

      ## Utilizing ODD Collector with Redash
      To fully harness the potential of OpenDataDiscovery in conjunction with Redash,
      users should utilize the [ODD Collector](https://github.com/opendatadiscovery/odd-collector). This dedicated agent relies exclusively on  Redash API
      to access and retrieve vital information about dashboards and queries, including their associated metadata.

      > It is essential to understand that since the ODD Collector does not execute additional analytical queries against the actual data,
      some metrics may not reflect precise values.
  - title: Configure
    content: |+
      ## ODD Platform
      To integrate ODD Collector with the ODD Platform, users must first establish a collector entity within the platform by following these steps:

      1. Navigate to the "Management" section and select "Collectors".
      2. Click on the "Add Collector" button to initiate the process.
      3. Input a unique name for the collector and, optionally, provide a namespace to further categorize and organize the entity. Additionally, you may include a brief description to give more context and information about the collector.
      4. Click "Save" to finalize the setup, and take note of the generated token. This token will be required for incorporating it into the ODD Collector's configuration YAML file, ensuring secure communication between the two components.

      ## ODD Collector
      The process of configuring the ODD Collector involves creating and customizing a single, well-structured YAML configuration file

      ````yaml
      # ODD Platform's host URL
      platform_host_url: https://your.odd.platform

      # Default pulling interval in minutes
      default_pulling_interval: 10

      # Collector's specific security token
      token: ""

      plugins:
        - type: redash
          # Data source's name
          name: redash_adapter
          # Optional Data source's description
          description: "Redash sample"
          # Redash server
          server: server
          # Redash API key
          api_key: api_key
      ````
    snippets:
      - template: |+
          ````yaml
          platform_host_url: {{ platform_url }}
          default_pulling_interval: 10
          token: <Security token>
          plugins:
            - type: redash
              name: {{ ds_name }}
              description: {{ plugin_description }}
              server: {{ plugin_server }}
              api_key: <API key>
          ````
        arguments:
          - parameter: platform_url
            type: STRING
            static: true
          - parameter: ds_name
            name: Data source name
            type: STRING
          - parameter: plugin_description
            name: Data source description
            type: STRING
          - parameter: plugin_server
            name: Server
            type: STRING