id: superset
name: Superset
description: |
  Superset integration
blocks:
  - title: Overview
    content: |+
      The Superset integration significantly enhances data discovery and observability capabilities for Superset data exploration and visualization platform,
      providing an efficient and powerful solution for users seeking to optimize their data management experience.

      ## Utilizing ODD Collector with Superset
      To fully harness the potential of OpenDataDiscovery in conjunction with Superset,
      users should utilize the [ODD Collector](https://github.com/opendatadiscovery/odd-collector).
      This dedicated agent relies on Superset's REST API to access and retrieve vital information about Dashboards, Charts and Datasets, including their associated metadata.
      By doing so, the ODD Collector ensures a non-intrusive approach that prevents any performance
      impact on the service.

      > It is essential to understand that since the ODD Collector does not execute additional analytical queries against the actual data,
      some metrics may not reflect precise values.
  - title: Configure
    content: |+
      ## ODD Platform
      To integrate ODD Collector with the ODD Platform, users must first establish a collector entity within the platform by following these steps:

      1. Navigate to the "Management" section and select "Collectors".
      2. Click on the "Add Collector" button to initiate the process.
      3. Input a unique name for the collector and, optionally, provide a namespace to further categorize and organize the entity. Additionally, you may include a brief description to give more context and information about the collector.
      4. Click "Save" to finalize the setup, and take note of the generated token. This token will be required for incorporating it into the ODD Collector's configuration YAML file, ensuring secure communication between the two components.

      ## ODD Collector
      The process of configuring the ODD Collector involves creating and customizing a single, well-structured YAML configuration file

      ````yaml
      # ODD Platform's host URL
      platform_host_url: https://your.odd.platform

      # Default pulling interval in minutes
      default_pulling_interval: 10

      # Collector's specific security token
      token: ""

      plugins:
        - type: superset
          # Data source's name
          name: superset_adapter
          # Optional Data source's description
          description: "Superset sample"
          # Superset server
          server: server
          # Superset username
          username: username
          # Superset user password
          password: password
      ````
    snippets:
      - template: |+
          ````yaml
          platform_host_url: {{ platform_url }}
          default_pulling_interval: 10
          token: <Security token>
          plugins:
            - type: superset
              name: {{ ds_name }}
              description: {{ plugin_description }}
              server: {{ plugin_server }}
              username: {{ plugin_username }}
              password: <Password for {{ plugin_username }}>
          ````
        arguments:
          - parameter: platform_url
            type: STRING
            static: true
          - parameter: ds_name
            name: Data source name
            type: STRING
          - parameter: plugin_description
            name: Data source description
            type: STRING
          - parameter: plugin_server
            name: Server
            type: STRING
          - parameter: plugin_username
            name: Username
            type: STRING
