id: tableau
name: Tableau
description: |
  Tableau integration
blocks:
  - title: Overview
    content: |+
      The Tableau integration significantly enhances data discovery and observability capabilities for Tableau,
      providing an efficient and powerful solution for users seeking to optimize their data management experience.

      ## Utilizing ODD Collector with Tableau
      To fully harness the potential of OpenDataDiscovery in conjunction with Tableau,
      users should utilize the [ODD Collector](https://github.com/opendatadiscovery/odd-collector).
      This dedicated agent relies on Tableau's GraphQL API to access and retrieve vital information about Sheets, Databases and Columns, including their associated metadata.
      By doing so, the ODD Collector ensures a non-intrusive approach that prevents any performance
      impact on the service.

      > It is essential to understand that since the ODD Collector does not execute additional analytical queries against the actual data,
      some metrics may not reflect precise values.
  - title: Configure
    content: |+
      ## ODD Platform
      To integrate ODD Collector with the ODD Platform, users must first establish a collector entity within the platform by following these steps:

      1. Navigate to the "Management" section and select "Collectors".
      2. Click on the "Add Collector" button to initiate the process.
      3. Input a unique name for the collector and, optionally, provide a namespace to further categorize and organize the entity. Additionally, you may include a brief description to give more context and information about the collector.
      4. Click "Save" to finalize the setup, and take note of the generated token. This token will be required for incorporating it into the ODD Collector's configuration YAML file, ensuring secure communication between the two components.

      ## ODD Collector
      The process of configuring the ODD Collector involves creating and customizing a single, well-structured YAML configuration file

      ````yaml
      # ODD Platform's host URL
      platform_host_url: https://your.odd.platform

      # Default pulling interval in minutes
      default_pulling_interval: 10

      # Collector's specific security token
      token: ""

      plugins:
        - type: tableau
          # Data source's name
          name: tableau_adapter
          # Optional Data source's description
          description: "tableau sample"
          # Tableau server
          server: server
          # Tableau site
          site: site
          # Optional Tableau user
          user: user
          # Optional Tableau user password
          password: password
          # Optional Tableau token name, used for connection to TableauServer with 2FA
          token_name: token_name
          # Tableau token value, used for connection to TableauServer with 2FA
          token_value: token_value
          # Tableau pagination size. This parameter may affect performance of the query as the query gets larger
          pagination_size: 10
      ````
    snippets:
      - template: |+
          ````yaml
          platform_host_url: {{ platform_url }}
          default_pulling_interval: 10
          token: <Security token>
          plugins:
            - type: tableau
              name: {{ ds_name }}
              description: {{ plugin_description }}
              server: {{ plugin_server }}
              site: {{ plugin_site }}
              user: {{ plugin_user }}
              password: <Password for {{ plugin_user }}>
              token_name: {{ plugin_token_name }}
              token_value: <Token value for {{ plugin_token_name }}>
              pagination_size: {{ plugin_pagination_size }}
          ````
        arguments:
          - parameter: platform_url
            type: STRING
            static: true
          - parameter: ds_name
            name: Data source name
            type: STRING
          - parameter: plugin_description
            name: Data source description
            type: STRING
          - parameter: plugin_server
            name: Tableau server
            type: STRING
          - parameter: plugin_site
            name: Tableau site
            type: STRING
          - parameter: plugin_user
            name: Tableau user
            type: STRING
          - parameter: plugin_token_name
            name: Tableau token name
            type: STRING
          - parameter: plugin_pagination_size
            name: Tableau pagination size
            type: STRING
